---
Profiles:
  TwoOrgsGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
    Consortiums:
      ${COIN_NAME_CAMELCASE}Consortium:
        Organizations:
        - *ShopOrg
        - *${COIN_NAME_CAMELCASE}Org
  TwoOrgsChannel:
    Consortium: ${COIN_NAME_CAMELCASE}Consortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *ShopOrg
      - *${COIN_NAME_CAMELCASE}Org

Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: cli/peers/ordererOrganizations/orderer-org/msp
- &ShopOrg
  Name: ShopOrgMSP
  ID: ShopOrgMSP
  MSPDir: cli/peers/peerOrganizations/shop-org/msp
  AnchorPeers:
  - Host: shop-peer
    Port: 7051
- &${COIN_NAME_CAMELCASE}Org
  Name: ${COIN_NAME_CAMELCASE}OrgMSP
  ID: ${COIN_NAME_CAMELCASE}OrgMSP
  MSPDir: cli/peers/peerOrganizations/${COIN_NAME}-org/msp
  AnchorPeers:
  - Host: ${COIN_NAME}-peer
    Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:
