OrdererOrgs:
- Name: OrdererOrg
  Domain: orderer-org
  CommonName: orderer-org
  Specs:
  - Hostname: orderer0
    CommonName: "{{.Hostname}}"
PeerOrgs:
- Name: ShopOrg
  Domain: shop-org
  Specs:
  - Hostname: shop-peer
    CommonName: "{{.Hostname}}"
  Template:
    Count: 2
  Users:
    Count: 1
- Name: ${COIN_NAME_CAMELCASE}Org
  Domain: ${COIN_NAME}-org
  Specs:
  - Hostname: ${COIN_NAME}-peer
    CommonName: "{{.Hostname}}"
  Template:
    Count: 2
  Users:
    Count: 1
