---
Profiles:
  TwoOrgsGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
    Consortiums:
      CryptocurrencyConsortium:
        Organizations:
        - *ShopOrg
        - *CryptocurrencyOrg
  TwoOrgsChannel:
    Consortium: CryptocurrencyConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *ShopOrg
      - *CryptocurrencyOrg

Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: cli/peers/ordererOrganizations/orderer-org/msp
- &ShopOrg
  Name: ShopOrgMSP
  ID: ShopOrgMSP
  MSPDir: cli/peers/peerOrganizations/shop-org/msp
  AnchorPeers:
  - Host: shop-peer
    Port: 7051
- &CryptocurrencyOrg
  Name: CryptocurrencyOrgMSP
  ID: CryptocurrencyOrgMSP
  MSPDir: cli/peers/peerOrganizations/cryptocurrency-org/msp
  AnchorPeers:
  - Host: cryptocurrency-peer
    Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:
